# Project information
site_name: ZevenbergenRP APV
site_url: 'https://wetboek.Zevenbergen.nl/'
site_description: 'APV Van Zevenbergen'
site_author: 'Zevenbergen'
# Congiguration
theme:
  name: material
#   features:
#     - navigation.tabs
  palette:
    - scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
# Repository
repo_url: 'https://github.com/RyanFHO/wetboek-apv/'
repo_name: 'Zevenbergen APV'
edit_uri: 'https://github.com/RyanFHO/wetboek-apv'
