# Project information
site_name: ZevenbergenRP APV
site_url: 'https://wetboek.Zevenbergen.nl/'
site_description: 'APV Van Zevenbergen'
site_author: 'Zevenbergen'
# Congiguration
theme:
  name: material
#   features:
#     - navigation.tabs
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
# Repository
repo_url: 'https://github.com/RyanFHO/wetboek-apv/'
repo_name: 'Zevenbergen APV'
edit_uri: 'https://github.com/RyanFHO/wetboek-apv'
# Copyright
copyright: Copyright &copy; 2023 Zevenbergen
#Indeling
nav:
  - Home: index.md
  - Algemene Plaatselijke Verordening: APV.md
