# Project information
site_name: Zevenbergen APV
site_description: 'APV Zevenbergen'
site_author: 'ZevenbergenRP'

# Copyright
copyright: Copyright &copy; 2023 Zevenbergen

# Repository
repo_url: 'https://github.com/RyanFHO/wetboek-apv'
repo_name: 'Zevenbergen APV'
edit_uri: 'https://github.com/RyanFHO/wetboek-apv/tree/main'

# Congiguration
theme:
  name: material
#   features:
#     - navigation.tabs
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
nav:
  - Home: index.md
  - Algemene Plaatselijke Verordening: apv.md
