theme:
  name: material
  palette:
    - scheme: default
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  language: nl
  
# Project information
site_name: Zevenbergen APV
site_description: 'APV Zevenbergen'
site_author: 'ZevenbergenRP'

# Copyright
copyright: Copyright &copy; 2023 Zevenbergen

# Repository
repo_url: 'https://github.com/RyanFHO/wetboek-apv'
repo_name: 'Zevenbergen APV'
edit_uri: 'https://github.com/RyanFHO/wetboek-apv/tree/main'

#Features
nav:
  - Home: index.md
  - Algemene Plaatselijke Verordening: apv.md
