theme:
  name: material

# Project information
site_name: Zevenbergen APV
site_description: 'APV Zevenbergen'
site_author: 'ZevenbergenRP'

# Copyright
copyright: Copyright &copy; 2023 Zevenbergen

# Repository
repo_url: 'https://github.com/RyanFHO/wetboek-apv'
repo_name: 'Zevenbergen APV'
edit_uri: 'https://github.com/RyanFHO/wetboek-apv/tree/main'

#Features
nav:
  - Home: index.md
  - Algemene Plaatselijke Verordening: apv.md
