# Project information
site_name: ZevenbergenRP APV
site_url: 'https://wetboek.Zevenbergen.nl/'
site_description: 'APV Van Zevenbergen'
site_author: 'Zevenbergen'
# Congiguration
theme:
  palette:
    primary: deep orange
# Repository
repo_url: 'https://github.com/RyanFHO/wetboek-apv/'
repo_name: 'Zevenbergen APV'
edit_uri: 'https://github.com/RyanFHO/wetboek-apv'
# Copyright
copyright: Copyright &copy; 2023 Zevenbergen

